version: "3.9"

services:
  db:
    image: mongo:7
    container_name: billpro
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - billpro_mongo:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: root
      MONGO_INITDB_DATABASE: testdb

volumes:
  billpro_mongo:
